### ISSUE TITLE
Deployment Documentation Unity Version

### ISSUE THREAD

**Issue by MichaelRomer** [dfki-asr/MOSIM#1]
The [deployment from source code documentation](https://github.com/dfki-asr/MOSIM/wiki/Installation-of-the-MOSIM-Framework#manual-deployment-from-source-code) mentions, that Unity Version 2019.18.1f must be installed. This is not a feasible version number and should probably be changed to 2019.4.18f1.

**Comment by jsprenger2** [comment]
In general, any Unity 2019 version should work, as long as it is consistently used for the MMUs and Adapter. I adjusted the Documentation accordingly. On my system, I am currently utilizing 2019.4.25f1.
